spring.datasource.url=jdbc:postgresql://dpg-d9ql069t0dsc7388m8ng-a:5432/typesprintdb
spring.datasource.username=typesprintdb_user
spring.datasource.password=26nyTRS6tQWO0J2ojiysRuBNrGrwgd8z

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true